magento:
  oauth_callback: http://your_rails_host/mage/oauth_callback
  host: http://your_magento_host
  consumer_key: your_consumer_key_from_magento_admin
  consumer_secret: your_consumer_secret_from_magento_admin

